candidate/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home,name='home'),
    path('new_candidate/',views.createCandidate,name='new_candidate'),
    path('<str:pk>/accept',views.AcceptProfile,name='accept_profile'),
    path('<str:pk>/accepted',views.RAcceptProfile,name='raccept_profile'),
    path('<str:pk>/reject',views.RejectProfile,name='reject_profile'),
    path('viewprofile/<str:pk>',views.ViewProfile,name='view_profile'),
    path('updateprofile/<str:pk>',views.UpdateCandidate,name='update_candidate'),
    path('deleteprofile/<str:pk>',views.DeleteCandidate,name='delete_candidate'),
    path('rejectedprofile/',views.RejectedProfile,name='rejected_profile'),
    path('reviewdelete/',views.ReviewDelete,name='review_delete'),
    path('createproject/<str:pk>/',views.CreateProject,name='create-project'),
    path('updateproject/<str:pk>/',views.UpdateProject,name='update-project'), 
    path('deleteproject/<str:pk>/',views.DeleteProject,name='delete-project'), 
    path('createskill/<str:pk>/',views.CreateSkill,name='create-skill'),
    path('updateskill/<str:pk>/',views.UpdateSkill,name='update-skill'), 
    path('deleteskill/<str:pk>/',views.DeleteSkill,name='delete-skill'), 
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

candiresume/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('candidate.urls')),
    path('user/',include('user.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.profile,name='profile'),
    # path('profile/<str:pk>/', views.userprofile, name='user-profile'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/', views.registerUser, name='register'),
    path('edit-account/', views.editAccount, name='edit-account'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

candidate/models.py
from django.db import models
from ckeditor.fields import RichTextField
import uuid
from django.utils import timezone


# Create your models here.
class Candidate(models.Model): 
    first_name = models.CharField(max_length=100, null=True, blank=True)
    middle_name = models.CharField(max_length=100,null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=500,null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    short_intro = models.CharField(max_length=100, null=True, blank=True)
    location = models.CharField(max_length=2000, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True,default='images/blank.png',upload_to='candidate_profile/')
    bio=RichTextField(null=True, blank=True)  
    status=models.IntegerField(null=True, blank=True, default=1) 
    created = models.DateTimeField(default=timezone.now)
    social_github = models.URLField(null=True, blank=True)
    social_linkedin = models.URLField(null=True, blank=True)
    social_website = models.URLField(null=True, blank=True)
    social_twitter = models.URLField(null=True, blank=True)
    social_youtube = models.URLField(null=True, blank=True)
    social_facebook = models.URLField(null=True, blank=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True , primary_key=True, editable=False)
    resume = models.FileField(null=True, blank=True, upload_to='doc')
    def __str__(self):
        return str(self.first_name)
    

    

class Skill(models.Model):
    owner = models.ForeignKey(Candidate, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True,editable=False)

    def __str__(self):
        return str(self.name)



class Project(models.Model):
    owner =  models.ForeignKey(Candidate,null=True,blank=True,on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = RichTextField(null=True, blank=True)
    demo_link = models.URLField(null=True, blank=True)
    source_link = models.URLField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default-image.png", upload_to='project_image/')
    tags = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(null=True, blank=True,default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True,editable=False)
    def __str__(self):
        return  self.title

class Tag(models.Model):
    pass

    def __str__(self):
        return self.name

candidate/forms.py
from dataclasses import field
from django.forms import ModelForm
from .models import Candidate, Skill, Project
from django import forms

class CandidateForm(ModelForm):
    class Meta:
        model = Candidate
        fields = ['first_name', 'middle_name', 'last_name', 'email', 'phone', 'short_intro',
        'location', 'profile_image', 'bio','social_github', 'social_linkedin',
        'social_website', 'social_twitter', 'social_youtube', 'social_facebook', 'resume' ]
        # fields='__all__'
        widget = {
            'first_name' : forms.TextInput(attrs={'class':'form-control'}),
        }

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'demo_link', 'source_link', 'featured_image', 'created_at', ]


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'description']

candidate/views.py
from cgitb import html
from django.shortcuts import render,redirect
from matplotlib.style import context
from django.db.models import Q
from .models import Candidate, Project,Skill
from django.contrib.auth.decorators import login_required
from .forms import CandidateForm, ProjectForm, SkillForm
from .utils import searchProfiles

# Create your views here.
def home(request):
    candidate, search_query = searchProfiles(request)
    context = {'candidate': candidate,'search_query': search_query}
    return render(request,'candidate/home.html',context)


def ViewProfile(request,pk):
    candidate = Candidate.objects.get(id=pk)
    context = {'candidate': candidate}
    return render(request,'candidate/view_profile.html',context)

@login_required(login_url='login')
def createCandidate(request):
   form = CandidateForm()
   if request.method == 'POST':
      form= CandidateForm(request.POST, request.FILES)
      if form.is_valid():
         form.save()
         return redirect('home')
   context = {'form': form}
   return render(request,'candidate/new_candidate.html', context)


@login_required(login_url='login')
def UpdateCandidate(request,pk):
   candidate = Candidate.objects.get(id=pk)
   form = CandidateForm(instance=candidate)
   if request.method == 'POST':
      form = CandidateForm(request.POST,request.FILES, instance=candidate)
      if form.is_valid():
         form.save()
         return redirect('home')
   context = {'form': form}
   return render(request,'candidate/new_candidate.html', context)



@login_required(login_url='login')
def DeleteCandidate(request,pk):
   candidate = Candidate.objects.get(id=pk)
   if request.method == 'POST':
         candidate.delete()
         return redirect('home')     
   context = {'candidate': candidate}
   return render(request, 'candidate/delete_candidate.html', context)

def AcceptProfile(request,pk):
    candidate = Candidate.objects.get(id=pk)
    candidate.status = 2
    candidate.save()
    candi = Candidate.objects.all()
    context = {'candidate': candi,}
    return render(request, 'candidate/home.html',context)

def RAcceptProfile(request,pk):
    candidate = Candidate.objects.get(id=pk)
    candidate.status = 2
    candidate.save()
    candi = Candidate.objects.all()
    context = {'candidate': candi,}
    return render(request, 'candidate/rejected.html',context)

def RejectProfile(request,pk):
    candidate = Candidate.objects.get(id=pk)
    candidate.status = 3
    candidate.save()
    candi = Candidate.objects.all()
    context = {'candidate': candi,}
    return render(request, 'candidate/home.html',context)

def RejectedProfile(request):
    candidate = Candidate.objects.all()
    context = {'candidate': candidate,}
    return render(request,'candidate/rejected.html',context)


def ReviewDelete(request):
    candidate = Candidate.objects.all()
    context = {'candidate': candidate,}
    return render(request,'candidate/review_delete.html',context)

@login_required(login_url='login')
def CreateProject(request,pk):
   candidate =Candidate.objects.get(id=pk)
   project = request.user.profile
   print(project)

   form = ProjectForm()
   if request.method == 'POST':
      form= ProjectForm(request.POST, request.FILES)
      if form.is_valid():
         project=form.save(commit=False)
         project.owner = candidate
         project.save()
         return redirect('view_profile',pk)
   context = {'form': form}
   return render(request,'candidate/create-project.html', context)


@login_required(login_url='login')
def UpdateProject(request,pk):
   proj =Project.objects.get(id=pk)
   of=proj.owner.id
   print('proj=',proj)
   candidate = proj.owner
   print('candidate=',candidate)
   form = ProjectForm(instance=proj)
   if request.method == 'POST':
      form= ProjectForm(request.POST, request.FILES, instance=proj)
      if form.is_valid():
         project=form.save()
         return redirect('view_profile',pk=of)
   context = {'form': form}
   return render(request,'candidate/create-project.html', context)


@login_required(login_url="login")
def DeleteProject(request, pk):
    project =Project.objects.get(id=pk)
    of=project.owner.id
    project.delete()
    return redirect('view_profile',pk=of)

@login_required(login_url='login')
def CreateSkill(request,pk):
   candidate =Candidate.objects.get(id=pk)
   project = request.user.profile
   form = SkillForm()
   if request.method == 'POST':
      form= SkillForm(request.POST, request.FILES)
      if form.is_valid():
         project=form.save(commit=False)
         project.owner = candidate
         project.save()
         return redirect('view_profile',pk)
   context = {'form': form}
   return render(request,'candidate/create-skill.html', context)


@login_required(login_url='login')
def UpdateSkill(request,pk):
   skill =Skill.objects.get(id=pk)
   of=skill.owner.id
   form = SkillForm(instance=skill)
   if request.method == 'POST':
      form= SkillForm(request.POST, request.FILES, instance=skill)
      if form.is_valid():
         skill=form.save()
         return redirect('view_profile',pk=of)
   context = {'form': form}
   return render(request,'candidate/create-skill.html', context)


@login_required(login_url="login")
def DeleteSkill(request, pk):
    skill =Skill.objects.get(id=pk)
    of=skill.owner.id
    skill.delete()
    return redirect('view_profile',pk=of)

candidate/templates/candidate/create-project.html
{% extends 'main.html' %}

    {% block css %}
    
    {% endblock %}


    {% block title %}
        Create Project
    {% endblock %}

    {% block content %}
    <form method="POST" enctype="multipart/form-data">
        {{ form.media }}
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" >
    {% endblock %}

candidate/templates/candidate/create-skill.html
{% extends 'main.html' %}

    {% block css %}
    
    {% endblock %}


    {% block title %}
        Create Project
    {% endblock %}

    {% block content %}
    <form method="POST" enctype="multipart/form-data">
        {{ form.media }}
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" >
    {% endblock %}

candidate/templates/candidate/delete_candidate.html
{% extends 'main.html' %}

    {% block css %}
    
    {% endblock %}


    {% block title %}
        Delete Candidate
    {% endblock %}

    {% block content %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ candidate.first_name ]} Profile ?"
                <a href="{% url 'home' %}">
                    Go Back
                </a>
                <input type="submit" value="Delete">
                    </form>
    {% endblock %}

candidate/templates/candidate/home.html
{% extends 'main.html' %}

    {% block css %}
    {% load static %}
        <link href="{% static 'candidate/style/home.css' %}" rel="stylesheet" type="text/css">

    {% endblock %}


    {% block title %}
        candiresume
    {% endblock %}

    {% block content %}
        <div class="container">
        {% for candidate in candidate %}
          {% if candidate.status is not 3 %}
        
            <div class="card-container">
              <img class="round" src="{{ candidate.profile_image.url }}" alt="{{ candidate.first_name }} " height = "200px" width="200px" />
              <h3>
                {% if candidate.first_name is not None %}

                {{candidate.first_name}}
                {% endif %}
                {% if candidate.middle_name is not None %}
                 {{candidate.middle_name}} 
                 {% endif %}
                 {% if candidate.last_name is not None %}
                 {{candidate.last_name}}</h3>
                 {% endif %}
              <p><h5><a href="{% url 'view_profile' candidate.id %}"> View</a></h5></p> 
              {% if candidate.resume %}
              <p><h5><a href="images/{{candidate.resume}}" target="_blank">Resume</a></h5></p>
              {% endif %}
              {% if candidate.short_intro is not None %}
              <p>{{ candidate.short_intro }} </p>
              {% endif %}
              <div class="buttons">
                {% if candidate.status == 1 %}
                  <a href="{% url 'accept_profile' candidate.id %}"><button class="primary">Accept</button></a>
                  {% elif candidate.status == 2 %}
                  <a href=""><button class="primary">Accepted</button></a>
                  
                {% endif %}
                <a href="{% url 'reject_profile' candidate.id %}"><button class="primary ghost">Reject </button></a>
               
              </div>
              <div class="skills">
                <h6>Skills</h6>
                <ul>
                  {% for skill in candidate.skill_set.all %}
                  <li>{{ skill.name }}</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endblock %}

candidate/templates/candidate/new_candidate.html
{% extends 'main.html' %}

    {% block css %}
    
    {% endblock %}


    {% block title %}
        New Candidate Registration
    {% endblock %}

    {% block content %}
    <div class="form-group">
        <form method="POST" enctype="multipart/form-data">
            {{ form.media }}
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" >
        </form>
        </div> 
    {% endblock %}

candidate/templates/candidate/rejected.html
{% extends 'main.html' %}

    {% block css %}
    {% load static %}
        <link href="{% static 'candidate/style/home.css' %}" rel="stylesheet" type="text/css">

    {% endblock %}


    {% block title %}
        candiresume
    {% endblock %}

    {% block content %}
        <div class="container">
        {% for candidate in candidate %}
          {% if candidate.status is 3 %}
        
          <div class="card-container">
            <img class="round" src="{{ candidate.profile_image.url }}" alt="{{ candidate.first_name }} " height = "200px" width="200px" />
            <h3>
              {% if candidate.first_name is not None %}

              {{candidate.first_name}}
              {% endif %}
              {% if candidate.middle_name is not None %}
               {{candidate.middle_name}} 
               {% endif %}
               {% if candidate.last_name is not None %}
               {{candidate.last_name}}</h3>
               {% endif %}
            <p><h5><a href="{% url 'view_profile' candidate.id %}"> View</a></h5></p> 
            {% if candidate.resume %}
            <p><h5><a href="images/{{candidate.resume}}">Resume</a></h5></p>
            {% endif %}
            {% if candidate.short_intro is not None %}
            <p>{{ candidate.short_intro }} </p>
            {% endif %}
            <div class="buttons">
              <a href="{% url 'raccept_profile' candidate.id %}"><button class="primary">Accept</button></a>
            
            <a href=""><button class="primary ghost">Delete </button></a>
           
          </div>
            <div class="skills">
              <h6>Skills</h6>
              <ul>
                {% for skill in candidate.skill_set.all %}
                <li>{{ skill.name }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endblock %}

candidate/templates/candidate/review_delete.html
{% extends 'main.html' %}

    {% block css %}
    {% load static %}
        <link href="{% static 'candidate/style/home.css' %}" rel="stylesheet" type="text/css">

    {% endblock %}


    {% block title %}
        candiresume
    {% endblock %}

    {% block content %}
        <div class="container">
        {% for candidate in candidate %}
        
        <div class="card-container">
          <img class="round" src="{{ candidate.profile_image.url }}" alt="{{ candidate.first_name }} " height = "200px" width="200px" />
          <h3>
            {% if candidate.first_name is not None %}

            {{candidate.first_name}}
            {% endif %}
            {% if candidate.middle_name is not None %}
             {{candidate.middle_name}} 
             {% endif %}
             {% if candidate.last_name is not None %}
             {{candidate.last_name}}</h3>
             {% endif %}
          <p><h5><a href="{% url 'view_profile' candidate.id %}"> View</a></h5></p> 
          {% if candidate.resume %}
          <p><h5><a href="images/{{candidate.resume}}">Resume</a></h5></p>
          {% endif %}
          {% if candidate.short_intro is not None %}
          <p>{{ candidate.short_intro }} </p>
          {% endif %}
          <div class="buttons">
            {% if candidate.status == 1 %}
              <a href="{% url 'accept_profile' candidate.id %}"><button class="primary">Accept</button></a>
              {% elif candidate.status == 2 %}
              <a href=""><button class="primary">Accepted</button></a>
              {% elif candidate.status == 3 %}
              <a href=""><button class="primary">Rejected</button></a>
            {% endif %}
            <a href="{% url 'delete_candidate' candidate.id %}"><button class="primary ghost">Delete</button></a>
           
          </div>
          <div class="skills">
            <h6>Skills</h6>
            <ul>
              {% for skill in candidate.skill_set.all %}
              <li>{{ skill.name }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

candidate/templates/candidate/update-project.html
{% extends 'main.html' %}

    {% block css %}
    
    {% endblock %}


    {% block title %}
     Update Project
    {% endblock %}

    {% block content %}
    
    {% endblock %}

candidate/templates/candidate/view_profile.html
{% extends 'main.html' %}
{% load static %}
    {% block css %}
        {% comment %} {% load static %} {% endcomment %}
        <link href="{% static 'candidate/style/view_profile.css' %}" rel="stylesheet" type="text/css">

        <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    {% endblock %}


    {% block title %}
        CandiProfile
    {% endblock %}

    {% block content %}
    <div class="">
        <div class="student-profile py-4">
            <div class="container">
              <div class="row">
                <div class="col-lg-4">
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent text-center">
                        {% comment %} {% load static %} {% endcomment %}
                      <img class="profile_img"  src="{{ candidate.profile_image.url }}" alt="{{ candidate.first_name }} " />
                      <h3>
                        {% if candidate.first_name is not None %}

                {{candidate.first_name}}
                {% endif %}
                {% if candidate.middle_name is not None %}
                 {{candidate.middle_name}} 
                 {% endif %}
                 {% if candidate.last_name is not None %}
                 {{candidate.last_name}}
                 {% endif %}
                      </h3>
                    </div>
                    <div class="card-body">
                      <p>
                      {% if candidate.social_github %}
                      <a href="{{ candidate.social_github }}" target="_blank" style="text-decoration:None;">
                        Github
                      </a>
                      {% endif %}
                      {% if candidate.social_linkedin %}
                          {% comment %} {% load static %} {% endcomment %}
                      <a href="{{ candidate.social_linkedin }}" target="_blank" style="text-decoration:None;"> linkedin </a>
                      {% endif %}
                      {% if candidate.social_website %}
                      <a href="{{ candidate.social_website }}" target="_blank"  style="text-decoration:None;">Website</a>
                      {% endif %}
                      {% if candidate.social_youtube %}
                      <a href="{{ candidate.social_youtube }}" target="_blank" style="text-decoration:None;">Youtube</a>
                      {% endif %}
                      {% if candidate.social_twitter %}
                      <a href="{{ candidate.social_twitter }}" target="_blank" style="text-decoration:None;">Twitter</a>
                      {% endif %}
                      {% if candidate.social_facebook %}
                      <a href="{{ candidate.social_facebook }}" target="_blank" style="text-decoration:None;"> facebook</a> </a>
                      {% endif %}
                      <p>
                        <a href="{% url 'update_candidate' candidate.id %}"><button type="button" class="above-button">Update</button></a>
                        <a href="{% url 'delete_candidate' candidate.id %}"><button type="button" class="above-button">Delete</button></a>
                      </p>
                      <p>
                          {% if candidate.status is 3 or candidate.status is 1 %}

                        <a href="{% url 'accept_profile' candidate.id %}"><button type="button" class="down-button">Accept</button></a>
                              {% elif candidate.status is 2 %}
                              <button type="button" class="down-button">Accepted</button>
                          {% endif %}
                      </p>
                      <p>
                        <a href="{% url 'reject_profile' candidate.id %}"> <button type="button" class="down-button">Reject</button></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-8">
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                      <h3 class="mb-0"><i class="far fa-clone pr-1"></i>General Information</h3>
                    </div>
                    <div class="card-body pt-0">
                      <table class="table table-bordered">
                        {% if candidate.email %}
                        <tr>
                          <th width="30%">Email</th>
                          <td width="2%">:</td>
                          <td>{{ candidate.email }}</td>
                        </tr>
                        {% endif %}
                        {% if candidate.phone %}
                        <tr>
                          <th width="30%">Phone Number</th>	</th>
                          <td width="2%">:</td>
                          <td>{{ candidate.phone }}</td>
                        </tr>
                        {% endif %}
                        {% if candidate.location %}
                        <tr>
                          <th width="30%">location</th>
                          <td width="2%">:</td>
                          <td>{{ candidate.location }}</td>
                        </tr>
                        {% endif %}
                        <tr>
                          <th width="30%">Created</th>
                          <td width="2%">:</td>
                          <td>{{ candidate.created }}</td>
                        </tr>
                        {% if candidate.status %}
                        <tr>  
                          <th width="30%">Status</th>
                          <td width="2%">:</td>
                          {% if candidate.status is 1 %}
                          <td>Not decided</td>
                            {% elif candidate.status is 2 %}
                            <td>Accepted</td>
                            {% elif candidate.status is 3 %}
                            <td>Rejected</td>
                        {% endif %}
                        </tr>
                        {% endif %}
                      </table>
                      <div class="deleteupdate" font-size="25px">

                        
                      </div>
                    </div>
                  </div>
                  {% if candidate.short_intro %}
                  <div style="height: 26px"></div>
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                      <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Intro</h3>
                    </div>
                    <div class="card-body pt-0">
                        <p>{{ candidate.short_intro }}.</p>                          
                    </div>
                    {% endif %}

                    {% if candidate.bio %}
                    <div style="height: 26px"></div>
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                      <h3 class="mb-0"><i class="far fa-clone pr-1"></i>About Candidate</h3>
                    </div>
                    <div class="card-body pt-0">
                        <p>{{ candidate.bio|safe }}</p>
                    </div>
                    {% endif %}

                    <div style="height: 26px"></div>
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                      <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Skills</h3>
                      <h4> <a href="{% url 'create-skill' candidate.id  %}"  style="text-decoration:None;"> Add Skills </a> </h4>
                    </div>
                    <div class="card-body pt-0">
                      {% for skill in candidate.skill_set.all %}
                        <p><b>{{skill.name}}</b></p></b>{{ skill.description }}</p>
                        <p>
                          <a href="{% url 'update-skill' skill.id  %}" style="text-decoration:None;">Edit-Skills</a>
                          &nbsp;&nbsp;&nbsp;&nbsp;
                          <a href="{% url 'delete-skill' skill.id  %}" style="text-decoration:None;">Delete-Skills</a>
                        </p>
                          <hr/>
                       {% endfor %} 
                    </div>
                  </div>
                </div>
                <div style="height: 26px"></div>
                  <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                      <h3 class="mb-0"><i class="far fa-clone pr-1"></i>Projects</h3>
                      <h4> <a href="{% url 'create-project' candidate.id %}"  style="text-decoration:None;"> Create Project </a> </h4>

                    </div>
                    <div class="card-body pt-0">
                      {% for project in candidate.project_set.all %}
                        <p>
                            <img src="{{ project.featured_image.url }}" height="300px" width="300px" align="center">
                      </p>
                      <p><b>{{project.title}}</b> 
                        ||
                        <i><b float="right">Created : {{ project.created_at }}</b></i>
                        <p>

                          <a href="{{ project.owner.demo_link }}" target="_blank" style="text-decoration:None;">Demo-link</a>
                          &nbsp;&nbsp;&nbsp;&nbsp;

                          <a href="{{ candidate.source_link }}" target="_blank" style="text-decoration:None;">Source-link</a>

                        </p>
                        <p></b>{{ project.description|safe }}</p>
                     </b>
                    </p>
                    <p>
                      <a href="{% url 'update-project' project.id  %}" style="text-decoration:None;">Edit-Project</a>
                      &nbsp;&nbsp;&nbsp;&nbsp;
                      <a href="{% url 'delete-project' project.id  %}" style="text-decoration:None;">Delete-Project</a>
                    </p>
                    <hr />
                      {% endfor %}
                      <hr />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
       
    </div>    
    {% endblock %}